title: dvijayak.net
subtitle: wearing my heart on my sleeve
description: Theme used by dvijayak.net

theme: jekyll-theme-dvijayak

markdown: kramdown
excerpt_separator: <!--excerpt-->

plugins:
  - jekyll-autoprefixer

autoprefixer:
  browsers:
    - last 2 versions
  only_production: true